; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Duck Tales:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1

.export _music_data_duck_tales:=music_data_duck_tales

music_data_duck_tales:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : The Moon
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_duck_tales
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env6,@env8,@env0 ; 00 : DrumHi
	.word @env12,@env6,@env8,@env0 ; 01 : DrumLo
	.word @env16,@env6,@env8,@env0 ; 02 : DrumMed
	.word @env14,@env6,@env11,@env0 ; 03 : BleepIntro
	.word @env17,@env6,@env1,@env0 ; 04 : Bleep
	.word @env7,@env6,@env8,@env0 ; 05 : LeadLo
	.word @env5,@env6,@env1,@env0 ; 06 : LeadIntro
	.word @env3,@env6,@env8,@env0 ; 07 : Lead
	.word @env2,@env6,@env8,@env0 ; 08 : Bass
	.word @env13,@env6,@env8,@env0 ; 09 : DrumIntro

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $00,$ca,$7f,$00,$02
@env4:
	.byte $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env5:
	.byte $00,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$00,$0a
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $00,$c7,$7f,$00,$02
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@env10:
	.byte $00,$ca,$c4,$00,$02
@env11:
	.byte $c1,$7f,$00,$00
@env12:
	.byte $00,$ca,$02,$c2,$00,$03
@env13:
	.byte $00,$ca,$02,$c5,$00,$03
@env14:
	.byte $00,$c7,$06,$c1,$00,$03
@env15:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env16:
	.byte $00,$ca,$02,$c6,$03,$c2,$00,$05
@env17:
	.byte $00,$c7,$02,$c5,$03,$c1,$00,$05

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $ff, $ab, $48, $8c, $26, $cd, $49, .lobyte(@env15), .hibyte(@env15), $e1, $00, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8c, $2b, $a3, $00, $2d, $a3, $00, $30, $a3, $00, $48, $30, $b7, $00, $2f, $8f, $00, $2f, $b9, $49, .lobyte(@env15)
	.byte .hibyte(@env15), $cd, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8c, $2d, $a3, $00, $2b, $a3, $00, $48, $32, $f3
	.byte $00, $2b, $f3, $00, $37, $b9, $48, $bb, $49, .lobyte(@env4), .hibyte(@env4), $ff, $b1, $00, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8c, $39, $a3, $00, $37, $8f, $00, $48, $3e, $ff, $9d, $49, .lobyte(@env4), .hibyte(@env4), $ff, $9d, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $00
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $cf, $8e, $23, $8f, $00, $24, $8f, $00, $26, $8f, $00, $26
	.byte $b7, $00, $2b, $a3, $00, $2a, $a3, $00, $2b, $a3, $00, $48, $2d, $a3, $00, $2f, $8f, $00, $2b, $cd, $49, .lobyte(@env9)
	.byte .hibyte(@env9), $ff, $89, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $2a, $8f, $00, $2b, $8f, $00, $48, $32
	.byte $b7, $00, $2b, $8f, $00, $2b, $cd, $49, .lobyte(@env9), .hibyte(@env9), $f7, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $91, $00, $8e, $2b, $8f, $00, $48, $2b, $cb, $00, $93, $2d, $8f, $00, $2b, $8f, $00, $2a, $cd, $49, .lobyte(@env9)
	.byte .hibyte(@env9), $e1, $00, $48, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $23, $cb, $00, $93, $21, $8f, $00, $1f
	.byte $8f, $00, $26, $cb, $00, $93, $2b, $a3, $00, $2d, $a3, $00, $48, $30, $b7, $00, $2f, $8f, $00, $2f, $cd, $49, .lobyte(@env9)
	.byte .hibyte(@env9), $cd, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $32, $a3, $00, $30, $a3, $00, $48, $2f, $8f
	.byte $00, $30, $8f, $00, $2f, $8f, $00, $2b, $a3, $00, $26, $cb, $00, $2d, $8f, $00, $2b, $8f, $00, $2a, $8f, $00, $28, $8f
	.byte $00, $2a, $b7, $00, $48, $2b, $8f, $00, $a7, $2b, $8f, $00, $a7, $2b, $a3, $00, $8d, $72, $50, $f8, $23, $32, $8d, $73
	.byte $8f, $75, $8f, $76, $8f, $77, $8f, $79, $8f, $7a, $8f, $7c, $8f, $7e, $8f, $00, $48, $7f
@song0ref308:
	.byte $2b, $8f, $00, $2b, $8f, $00, $a7, $2d, $8f, $00, $2d, $8f, $00, $93, $29, $cb, $00, $26, $a3, $00, $29, $8f, $00, $24
	.byte $83, $25, $83, $00, $24, $81, $00, $22, $8f, $00, $48, $24, $a3, $00, $22, $8f, $00, $24, $8f, $00, $93, $22, $8f, $00
	.byte $93, $26, $ff, $9b, $00, $93, $48
	.byte $41, $0e
	.word @song0ref308
	.byte $2e, $a3, $00, $29, $a3, $00, $29, $a3, $00, $29, $8f, $00, $2e, $8f, $00, $30, $91, $48, $f5, $00, $2e, $8f, $00, $32
	.byte $f3, $00, $32, $8f, $00, $32, $8f, $00, $32, $91, $48, $cf, $49, .lobyte(@env9), .hibyte(@env9), $ff, $9d, $00, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $8e, $0f, $a3, $00, $11, $a3, $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $86
@song0ref423:
	.byte $2b, $8f, $00, $32, $8f, $00, $37, $8f, $00, $39, $8f, $00, $32, $8f, $00, $37, $8f, $00, $39
@song0ref442:
	.byte $8f, $00, $3c, $8f, $00, $32, $8f, $00, $3c, $8f, $00, $3b, $8f, $00, $32, $8f, $00, $3b, $8f, $00, $39, $8f, $00, $37
	.byte $8f, $00
	.byte $41, $2d
	.word @song0ref423
	.byte $41, $2d
	.word @song0ref423
	.byte $41, $2d
	.word @song0ref423
	.byte $41, $2d
	.word @song0ref423
	.byte $88
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
@song0ch1loop:
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $37, $8f, $00, $2e, $8f, $00, $33, $8f, $00, $39, $8f, $00, $30, $8f, $00, $39, $8f, $00, $3c, $8f, $00, $3b, $8f, $00
	.byte $37, $8f, $00, $32, $8f, $00, $30, $8f, $00, $2f, $8f, $00, $2b, $8f, $00, $26, $8f, $00, $24, $8f, $00, $23, $8f, $00
	.byte $8a, $22, $8f, $00, $22, $8f, $00, $a7, $24, $8f, $00, $24, $8f, $00, $93, $22, $a3, $00, $86, $2d, $8f, $00, $2e, $8f
	.byte $00, $35, $8f, $00, $93, $39, $8f, $00, $3a, $8f, $00, $40, $4d, $8f, $00, $8a, $1b, $a3, $00, $1b, $8f, $00, $1b, $8f
	.byte $00, $93, $1b, $8f, $00, $93, $1e, $ff, $9b, $00, $93, $27, $8f, $00, $27, $8f, $00, $a7, $24, $8f, $00, $24, $8f, $00
	.byte $93, $26, $a3, $00, $26, $a3, $00, $26, $a3, $00, $26, $8f, $00, $29, $8f, $00, $2b, $91, $e1, $00, $93, $2b, $8f, $00
	.byte $2a, $f3, $00, $2a, $8f, $00, $2a, $8f, $00, $2b, $8f, $00, $88
	.byte $41, $15
	.word @song0ref423
	.byte $32
	.byte $41, $1a
	.word @song0ref442
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $ab, $90, $1f, $b7, $00, $26, $b7, $00, $2b, $ff, $9b, $00, $93, $1d, $b7, $00, $24, $b7, $00, $29, $ff, $9b
	.byte $00, $93, $1c, $b7, $00, $23, $b7, $00, $28, $ff, $9b, $00, $93, $1b, $b7, $00, $22, $b7, $00, $27, $ff, $9b, $00, $93
@song0ref753:
	.byte $2b, $8f, $00, $2b, $8f, $00, $2b, $8f, $00, $2b, $8f, $00
	.byte $41, $0c
	.word @song0ref753
	.byte $41, $0c
	.word @song0ref753
	.byte $41, $0c
	.word @song0ref753
@song0ch2loop:
	.byte $41, $0c
	.word @song0ref753
	.byte $41, $0c
	.word @song0ref753
@song0ref781:
	.byte $2a, $8f, $00, $2a, $8f, $00, $2a, $8f, $00, $2a, $8f, $00
	.byte $41, $0c
	.word @song0ref781
@song0ref796:
	.byte $28, $8f, $00, $28, $8f, $00, $28, $8f, $00, $28, $8f, $00
	.byte $41, $0c
	.word @song0ref796
@song0ref811:
	.byte $26, $8f, $00, $26, $8f, $00, $26, $8f, $00, $26, $8f, $00
	.byte $41, $0c
	.word @song0ref811
@song0ref826:
	.byte $24, $8f, $00, $24, $8f, $00, $24, $8f, $00, $24, $8f, $00
	.byte $41, $0c
	.word @song0ref826
@song0ref841:
	.byte $25, $8f, $00, $25, $8f, $00, $25, $8f, $00, $25, $8f, $00
	.byte $41, $0c
	.word @song0ref841
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref753
	.byte $41, $0c
	.word @song0ref753
@song0ref874:
	.byte $29, $8f, $00, $29, $8f, $00, $29, $8f, $00, $29, $8f, $00
	.byte $41, $0c
	.word @song0ref874
	.byte $41, $0c
	.word @song0ref796
	.byte $41, $0c
	.word @song0ref796
@song0ref895:
	.byte $27, $8f, $00, $27, $8f, $00, $27, $8f, $00, $27, $8f, $00
	.byte $41, $0c
	.word @song0ref895
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref841
	.byte $41, $0c
	.word @song0ref811
	.byte $27, $8f, $00, $a7, $29, $8f, $00, $a7, $2b, $b7, $00, $1f, $8f, $00, $1f, $8f, $00, $1f, $8f, $00, $1f, $8f, $00, $1f
	.byte $8f, $00, $1f, $8f, $00, $1f, $8f, $00
@song0ref954:
	.byte $24, $8f, $00, $24, $8f, $00, $a7, $29, $8f, $00, $29, $8f, $00, $93, $22, $a3, $00, $22, $8f, $00, $22, $8f, $00, $22
	.byte $8f, $00, $22, $8f, $00, $22, $8f, $00, $22, $8f, $00, $22, $8f, $00
	.byte $41, $0c
	.word @song0ref826
	.byte $41, $0c
	.word @song0ref826
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $26
	.word @song0ref954
	.byte $41, $0c
	.word @song0ref826
	.byte $41, $0c
	.word @song0ref826
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref811
	.byte $41, $0c
	.word @song0ref895
	.byte $41, $0c
	.word @song0ref895
	.byte $27, $8f, $00, $bb, $27, $a3, $00, $29, $a3, $00, $42
	.word @song0ch2loop
@song0ch3:
@song0ref1038:
	.byte $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $ff, $ff, $ab, $ff, $db, $92, $19, $8b, $00, $83, $14, $8b, $00, $83, $19
	.byte $8b, $00, $83, $14, $8b, $00, $83
@song0ref1069:
	.byte $82, $14, $8b, $00, $83, $80, $20, $83, $00, $8b, $84, $19, $8f, $00, $80, $20, $83, $00, $8b
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
@song0ref1094:
	.byte $82, $14, $8b, $00, $83, $80, $20, $83, $00, $8b, $84, $19, $8f, $00, $19, $8f, $00
@song0ch3loop:
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0f
	.word @song0ref1069
	.byte $41, $0e
	.word @song0ref1094
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $0d
	.word @song0ref1038
	.byte $ff, $ab, $ff, $ff, $bf
@song0ch4loop:
@song0ref1280:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref1280
	.byte $41, $0c
	.word @song0ref1280
	.byte $ff, $ff, $bf, $42
	.word @song0ch4loop
